---
- name: exemple sans become
  hosts: all

  vars:
   - service:
           name: apache
           rpm: apache2


  tasks:
  - name: apache2
    apt:
         name:  "{{service.rpm}}"
         state: present
  - name: ajout index.html
    template:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0777
        #notify: start_apache

  - name: configuration de virtualhost
    copy:
        src: /home/ubuntu/site1.conf
        dest: /etc/apache2/sites-available/site1.conf
        mode: 0777

