---

- name: copie artifact
  hosts: all
  become: true
  vars: 
    - source:  ../workspace/tp_jenkins_ansible/webapp/target/
    - destination: /opt/tomcat/latest/webapps/

  tasks:
        - name: copie webapp.war
          copy:
              src: "{{source}}"
              dest: "{{destination}}"
